cc_library(
    name = "git",
    hdrs = ["git.h"],
    srcs = ["git.cc"],
    deps = [
	    "@com_google_absl//absl/flags:flag",
	    "@com_google_absl//absl/status",
	    "//third_party:libgit2"
    ],
)

